# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-26 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Belt', '0002_auto_20180126_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Belt.Belt')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Belt.Book')),
            ],
        ),
    ]
