# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-26 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Belt', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
