# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-26 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Belt', '0005_auto_20180126_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='belt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belt_reviews', to='Belt.Belt'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belt_reviews', to='Belt.Book'),
        ),
    ]
